### ISSUE TITLE
Package compile time issue in gradle 8 and greater version

### ISSUE THREAD

**Issue by gurdeep7s** [mtzinfotech/aws_s3_private_flutter#2]
Please help me on this. I am unable to integrate this in the project. 

,* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@3f72ffcb of type BuildFlowService.Parameters
   > A problem occurred configuring project ':aws_s3_private_flutter'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by gurdeep7s** [comment]
@mtzinfotech @RomilPipaliya could you please help me on this.

**Comment by mtzinfotech** [comment]
> @mtzinfotech @RomilPipaliya could you please help me on this.

Please use [flutter_aws_s3_client](https://pub.dev/packages/flutter_aws_s3_client)
Now support web platform also

**Comment by gurdeep7s** [comment]
In my app, We are using the s3 bucket for just storing the images from the web app (using mysql database for storing the data and saving the url in the db for accessing).
I run this code as sample app and able to fetch the private  image link of s3 bucket with the secret key ,access key ,host, bucket id. 
**flutter_aws_s3_client** is deprecated and aws ampliy need authentication. In my mobile app (ios and android using flutter),i don't have use database at aws for authentication.(User saved in the mysql db ).
Please update the package or guide me. @mtzinfotech @RomilPipaliya

**Comment by mtzinfotech** [comment]
> In my app, We are using the s3 bucket for just storing the images from the web app (using mysql database for storing the data and saving the url in the db for accessing). I run this code as sample app and able to fetch the private image link of s3 bucket with the secret key ,access key ,host, bucket id. **flutter_aws_s3_client** is deprecated and aws ampliy need authentication. In my mobile app (ios and android using flutter),i don't have use database at aws for authentication.(User saved in the mysql db ). Please update the package or guide me. @mtzinfotech @RomilPipaliya

Did you check [amplify_storage_s3](https://pub.dev/packages/amplify_storage_s3)
which support most of method available in aws
